### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 20000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "4d860fca2f99404bbabf731b7d51549e",
  "accountNumber": "1000000002",
  "amount": 30000
}

###query transaction
GET http://localhost:8080/transaction/c6bc69d1b4374ee9b6ed76643347158f